language: csharp
solution: FirebaseAdmin/FirebaseAdmin.sln

matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      script:
       - dotnet build FirebaseAdmin/FirebaseAdmin
       - dotnet build FirebaseAdmin/FirebaseAdmin.Snippets
       - dotnet build FirebaseAdmin/FirebaseAdmin.IntegrationTests
       - dotnet test FirebaseAdmin/FirebaseAdmin.Tests
