language: csharp
solution: FirebaseAdmin/FirebaseAdmin.sln

matrix:
  include:
    - dotnet: 2.1.0
      mono: none
      script:
       - dotnet build FirebaseAdmin/FirebaseAdmin
       - dotnet test FirebaseAdmin/FirebaseAdmin.Tests
